"use client";

import Login from "../components/login";
import { ReactNode } from "react";
import "./styles/globals.css";
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Login />
        {children}
      </body>
    </html>
  );
}
