"use client";

import { ReactNode } from "react";
import "./styles/globals.css";
import { AuthProvider } from "@/app/context/authContext";
import Navbar from "@/components/navbar/navbar";
import { ToastProvider } from "./context/toastContext";
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <ToastProvider>
          <AuthProvider>
            <Navbar />
            {children}
          </AuthProvider>
        </ToastProvider>
      </body>
    </html>
  );
}

//@todo use pathname/ router to conditonally render image in navbar
