"use client";

import { ReactNode } from "react";
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
import Image from "next/image";

export default function ProfilePageLayout({
  children,
}: {
  children: ReactNode;
}) {
  return (
    <div>
      <Image
        width={150}
        height={150}
        className="m-2"
        src={"/oflogo.svg"}
        alt="OnlyMemes!"
      />
      {children}
    </div>
  );
}
