"use client";

import { ReactNode } from "react";
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
export default function MemePageLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <div className="py-20 px-40">{children}</div>
      </body>
    </html>
  );
}
